vich_uploader:
    db_driver: orm

    metadata:
        type: attriute

    mappings:
        post_thumbnail:
            uri_prefix: '%medias_directory%'
            upload_destination: '%kernel.project_dir%/public%medias_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
